// Mocks generated by Mockito 5.4.6 from annotations
// in spiceease/test/features/tracker/modals_unit_tests_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:spiceease/data/models/medication_model.dart' as _i7;
import 'package:spiceease/data/models/subtask_model.dart' as _i5;
import 'package:spiceease/data/models/task_model.dart' as _i8;
import 'package:spiceease/features/tracker/presentation/controllers/tracker_controller.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRef_0<State extends Object?> extends _i1.SmartFake
    implements _i2.Ref<State> {
  _FakeRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_1 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TrackerController].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrackerController extends _i1.Mock implements _i3.TrackerController {
  MockTrackerController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Ref<Object?> get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeRef_0<Object?>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.Ref<Object?>);

  @override
  DateTime get selectedDate => (super.noSuchMethod(
        Invocation.getter(#selectedDate),
        returnValue: _FakeDateTime_1(
          this,
          Invocation.getter(#selectedDate),
        ),
      ) as DateTime);

  @override
  _i4.Future<void> addEnergy(
    int? energyLevel,
    String? notes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addEnergy,
          [
            energyLevel,
            notes,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateEnergy(
    String? id,
    int? energyLevel,
    String? notes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEnergy,
          [
            id,
            energyLevel,
            notes,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteEnergy(
    String? id,
    _i2.WidgetRef? ref,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteEnergy,
          [
            id,
            ref,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addMood(
    int? moodLevel,
    String? notes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMood,
          [
            moodLevel,
            notes,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateMood(
    String? id,
    int? moodLevel,
    String? notes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMood,
          [
            id,
            moodLevel,
            notes,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteMood(
    String? id,
    _i2.WidgetRef? ref,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMood,
          [
            id,
            ref,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addSymptom(
    String? name,
    String? category,
    int? severity,
    String? notes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addSymptom,
          [
            name,
            category,
            severity,
            notes,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateSymptom(
    String? id,
    String? name,
    String? category,
    int? severity,
    String? notes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSymptom,
          [
            id,
            name,
            category,
            severity,
            notes,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteSymptom(
    String? id,
    _i2.WidgetRef? ref,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSymptom,
          [
            id,
            ref,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addMedication({
    required String? name,
    required double? dose,
    required String? unit,
    required String? frequency,
    List<int>? customDays,
    required int? timesPerDay,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMedication,
          [],
          {
            #name: name,
            #dose: dose,
            #unit: unit,
            #frequency: frequency,
            #customDays: customDays,
            #timesPerDay: timesPerDay,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateMedication({
    required String id,
    required DateTime forDate,
    required bool isCompleted,
    bool skipRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMedication,
          [],
          {
            #id: id,
            #forDate: forDate,
            #isCompleted: isCompleted,
            #skipRefresh: skipRefresh,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteMedication(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteMedication,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addTask({
    required String? title,
    required String? description,
    required String? status,
    DateTime? dueDate,
    DateTime? completedAt,
    String? estimatedTime,
    required int? priority,
    required List<_i5.SubtaskModel>? subtasks,
    DateTime? startTime,
    DateTime? endTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTask,
          [],
          {
            #title: title,
            #description: description,
            #status: status,
            #dueDate: dueDate,
            #completedAt: completedAt,
            #estimatedTime: estimatedTime,
            #priority: priority,
            #subtasks: subtasks,
            #startTime: startTime,
            #endTime: endTime,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateTask(
    String id,
    String title,
    String description,
    String status,
    DateTime? dueDate,
    DateTime? completedAt,
    String? estimatedTime,
    int priority,
    List<_i5.SubtaskModel>? subtasks,
    DateTime? startTime,
    DateTime? endTime, {
    bool skipRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [
            id,
            title,
            description,
            status,
            dueDate,
            completedAt,
            estimatedTime,
            priority,
            subtasks,
            startTime,
            endTime,
          ],
          {
            #skipRefresh: skipRefresh,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTask(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateSubtask(
    String taskId,
    _i5.SubtaskModel subtask,
    String title,
    bool completed,
    String status,
    String rawTimeValue,
    DateTime? startTime,
    DateTime? endtime, {
    bool skipRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSubtask,
          [
            taskId,
            subtask,
            title,
            completed,
            status,
            rawTimeValue,
            startTime,
            endtime,
          ],
          {
            #skipRefresh: skipRefresh,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> createSubtask(
    String? taskId,
    String? title,
    String? rawTimeValue,
    int? priority,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSubtask,
          [
            taskId,
            title,
            rawTimeValue,
            priority,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteSubtask(
    String? subtaskId,
    String? parentTaskId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSubtask,
          [
            subtaskId,
            parentTaskId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addHabit({
    required String? title,
    required String? description,
    required int? frequency,
    List<int>? customDays,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addHabit,
          [],
          {
            #title: title,
            #description: description,
            #frequency: frequency,
            #customDays: customDays,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateHabit(
    String id,
    String title,
    String description,
    int frequency,
    List<int>? customDays,
    bool markAsCompleted, {
    bool skipRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateHabit,
          [
            id,
            title,
            description,
            frequency,
            customDays,
            markAsCompleted,
          ],
          {
            #skipRefresh: skipRefresh,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteHabit(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteHabit,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  String generateId() => (super.noSuchMethod(
        Invocation.method(
          #generateId,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #generateId,
            [],
          ),
        ),
      ) as String);

  @override
  _i4.Future<String> getUserId() => (super.noSuchMethod(
        Invocation.method(
          #getUserId,
          [],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getUserId,
            [],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  bool isMedicationDue(_i7.MedicationModel? med) => (super.noSuchMethod(
        Invocation.method(
          #isMedicationDue,
          [med],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> toggleMedicationCompletion(
    _i7.MedicationModel? medication,
    bool? isCompleted,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleMedicationCompletion,
          [
            medication,
            isCompleted,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateTaskStatus(
    String? oldStatus,
    int? index,
    String? newStatus,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTaskStatus,
          [
            oldStatus,
            index,
            newStatus,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i8.TaskModel>> getAllTasks() => (super.noSuchMethod(
        Invocation.method(
          #getAllTasks,
          [],
        ),
        returnValue: _i4.Future<List<_i8.TaskModel>>.value(<_i8.TaskModel>[]),
      ) as _i4.Future<List<_i8.TaskModel>>);

  @override
  _i4.Future<List<_i8.TaskModel>> getTasksByStatus(String? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksByStatus,
          [status],
        ),
        returnValue: _i4.Future<List<_i8.TaskModel>>.value(<_i8.TaskModel>[]),
      ) as _i4.Future<List<_i8.TaskModel>>);
}
