name: spiceease
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  provider: ^6.1.1
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  shared_preferences: ^2.2.1
  path_provider: ^2.1.1
  dio: ^5.4.0
  flutter_secure_storage: ^10.0.0-beta.4
  fl_chart: ^0.71.0
  analyzer: ^7.4.1
  flutter_riverpod: ^2.6.1
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_localization: ^0.3.2

dev_dependencies:
  flutter_dotenv: ^5.2.1
  build_runner: ^2.4.15
  mocktail: any

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/images/