/// This file demonstrates two main testing strategies for the FirebaseDatabaseService interface:
///
/// 1. **Mockito-based contract tests** (unit tests)
///    - Use a mock implementation generated by Mockito.
///    - Verify that the service methods are called with the correct arguments and return the expected results.
///    - These tests do **not** check the actual logic or data storage—only the contract/interface.
///
/// 2. **Fake-based logic tests** (integration-style unit tests)
///    - Use a simple in-memory fake implementation (`FakeFirebaseDatabaseService`).
///    - The fake stores data in a Dart map, simulating a database.
///    - These tests verify that the logic of methods like `batchUpdate` and CRUD operations actually changes the data as expected.
///    - No real database or network is used; everything is in-memory and fast.
///
/// # When to use which?
/// - Use **mock tests** to verify that your code interacts with the service correctly (good for testing code that depends on the service).
/// - Use **fake tests** to verify the logic of your service implementation (good for testing your own service logic).
///
/// # How to run
/// - Run with `flutter test` as usual.
/// - No Firestore or external dependencies are required.
///
/// # Example output
/// - If you change the logic of `batchUpdate` or CRUD in the fake, the fake test will fail, showing you that your logic is broken.
/// - If you change the method signature or forget to call a method, the mock test will fail.
///
/// # See also
/// - https://docs.flutter.dev/testing
/// - https://pub.dev/packages/mockito
/// - https://martinfowler.com/bliki/TestDouble.html

import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:spiceease/core/database/database_service.dart';
import 'package:spiceease/core/database/firebase_database_service.dart';

// This import will be generated by build_runner
import 'database_sdk_service_tests.mocks.dart';

/// A simple in-memory fake implementation of [FirebaseDatabaseService].
/// Stores documents in a Dart map, simulating a Firestore-like database.
class FakeFirebaseDatabaseService implements FirebaseDatabaseService {
  final Map<String, Map<String, dynamic>> _store = {};

  @override
  Future<void> initialize() async {}

  @override
  String generateId() {
    return DateTime.now().millisecondsSinceEpoch.toString();
  }

  @override
  Future<Map<String, dynamic>?> getDocument(String path) async {
    final data = _store[path];
    if (data == null) return null;
    return {'id': path.split('/').last, ...data};
  }

  @override
  Future<Map<String, dynamic>> createDocument(
      String collection, Map<String, dynamic> data) async {
    final id = data['id'] as String;
    _store['$collection/$id'] = Map<String, dynamic>.from(data)..remove('id');
    return {'id': id, ..._store['$collection/$id']!};
  }

  @override
  Future<Map<String, dynamic>> updateDocument(
      String path, Map<String, dynamic> data) async {
    final id = data['id'] as String;
    _store[path] = Map<String, dynamic>.from(data)..remove('id');
    return {'id': id, ..._store[path]!};
  }

  @override
  Future<void> deleteDocument(String path) async {
    _store.remove(path);
  }

  @override
  Future<List<Map<String, dynamic>>> query({
    required String collection,
    String? endBefore,
    List<QueryFilter>? filters,
    int? limit,
    List<QueryOrder>? orderBy,
    String? startAfter,
  }) async {
    return _store.entries
        .where((e) => e.key.startsWith('$collection/'))
        .map((e) => {'id': e.key.split('/').last, ...e.value})
        .toList();
  }

  @override
  Future<void> batchUpdate(List<Map<String, dynamic>> updates) async {
    for (final update in updates) {
      final path = update['path'] as String;
      final data = Map<String, dynamic>.from(update['data'] as Map);
      _store[path] = data;
    }
  }
}

@GenerateMocks([
  FirebaseDatabaseService,
])
void main() {
  // --------------------------------------------------------------------------
  // 1. Contract tests using a mock (Mockito)
  // --------------------------------------------------------------------------
  group('FirebaseDatabaseService (SDK) Tests with mockito', () {
    late MockFirebaseDatabaseService mockService;

    setUp(() {
      mockService = MockFirebaseDatabaseService();
    });

    /// Example test structure for contract tests:
    /// test('description', () async {
    ///   // 1. Arrange: Set up any needed mock responses or data.
    ///   // 2. Act: Call the method you want to test.
    ///   // 3. Assert: Check the result and verify the correct calls were made.
    /// });

    /// Verifies that getDocument returns the expected map when found.
    test('getDocument returns decoded map on success', () async {
      // Arrange: Set up the mock to return a specific map.
      when(mockService.getDocument('col/doc1'))
          .thenAnswer((_) async => {'id': 'doc1', 'foo': 'bar', 'num': 42});

      // Act: Call the method under test.
      final result = await mockService.getDocument('col/doc1');

      // Assert: Check the result and verify the correct call.
      expect(result, {'id': 'doc1', 'foo': 'bar', 'num': 42});
      verify(mockService.getDocument('col/doc1')).called(1);
    });

    /// Verifies that getDocument returns null when the document is not found.
    test('getDocument returns null if not found', () async {
      // Arrange: Set up the mock to return null.
      when(mockService.getDocument('col/missing'))
          .thenAnswer((_) async => null);

      // Act: Call the method under test.
      final result = await mockService.getDocument('col/missing');

      // Assert: Should be null and the call should be verified.
      expect(result, isNull);
      verify(mockService.getDocument('col/missing')).called(1);
    });

    /// Verifies that createDocument returns the created map.
    test('createDocument returns created map', () async {
      // Arrange: Set up the mock to return a specific map.
      when(mockService.createDocument('col', {'id': 'newId', 'foo': 'baz'}))
          .thenAnswer((_) async => {'id': 'newId', 'foo': 'baz'});

      // Act: Call the method under test.
      final result = await mockService
          .createDocument('col', {'id': 'newId', 'foo': 'baz'});

      // Assert: Check the result and verify the correct call.
      expect(result, {'id': 'newId', 'foo': 'baz'});
      verify(mockService.createDocument('col', {'id': 'newId', 'foo': 'baz'}))
          .called(1);
    });

    /// Verifies that updateDocument returns the updated map.
    test('updateDocument returns updated map', () async {
      // Arrange: Set up the mock to return a specific map.
      when(mockService
              .updateDocument('col/doc2', {'id': 'doc2', 'foo': 'updated'}))
          .thenAnswer((_) async => {'id': 'doc2', 'foo': 'updated'});

      // Act: Call the method under test.
      final result = await mockService
          .updateDocument('col/doc2', {'id': 'doc2', 'foo': 'updated'});

      // Assert: Check the result and verify the correct call.
      expect(result, {'id': 'doc2', 'foo': 'updated'});
      verify(mockService.updateDocument(
          'col/doc2', {'id': 'doc2', 'foo': 'updated'})).called(1);
    });

    /// Verifies that deleteDocument completes without error.
    test('deleteDocument completes without error', () async {
      // Arrange: Set up the mock to complete successfully.
      when(mockService.deleteDocument('col/doc3'))
          .thenAnswer((_) async => null);

      // Act: Call the method under test.
      await mockService.deleteDocument('col/doc3');

      // Assert: Verify the correct call.
      verify(mockService.deleteDocument('col/doc3')).called(1);
    });

    /// Verifies that query returns a list of decoded documents.
    test('query returns list of decoded documents', () async {
      // Arrange: Set up the mock to return a list of maps.
      when(mockService.query(collection: 'col')).thenAnswer((_) async => [
            {'id': 'a', 'x': 1},
            {'id': 'b', 'x': 2},
          ]);

      // Act: Call the method under test.
      final results = await mockService.query(collection: 'col');

      // Assert: Check the result and verify the correct call.
      expect(results, [
        {'id': 'a', 'x': 1},
        {'id': 'b', 'x': 2},
      ]);
      verify(mockService.query(collection: 'col')).called(1);
    });

    /// Verifies that batchUpdate is called with the correct payload.
    test('batchUpdate sends correct writes payload', () async {
      // Arrange: Prepare the updates list and set up the mock.
      final updates = [
        {
          'path': 'col/a',
          'data': {'foo': 'A'}
        },
        {
          'path': 'col/b',
          'data': {'bar': 123}
        },
      ];

      when(mockService.batchUpdate(updates)).thenAnswer((_) async {});

      // Act: Call the method under test.
      await mockService.batchUpdate(updates);

      // Assert: Verify the correct call.
      verify(mockService.batchUpdate(updates)).called(1);
    });
  });

  // --------------------------------------------------------------------------
  // 2. Logic tests using a fake (in-memory implementation)
  // --------------------------------------------------------------------------
  group('FakeFirebaseDatabaseService (SDK) Tests', () {
    late FakeFirebaseDatabaseService fakeService;

    setUp(() {
      fakeService = FakeFirebaseDatabaseService();
    });

    /// Example test structure for fake-based logic tests:
    /// test('description', () async {
    ///   // 1. Arrange: Set up any needed initial state or data.
    ///   // 2. Act: Call the method you want to test.
    ///   // 3. Assert: Check the result and verify the state of the fake.
    /// });

    /// Verifies that createDocument actually stores and returns the document.
    test('createDocument actually creates and returns the document', () async {
      // Arrange: Nothing to set up, just call createDocument.

      // Act: Create a document.
      final result = await fakeService.createDocument('col', {'id': 'newId', 'foo': 'baz'});

      // Assert: The returned map should match, and the document should be stored.
      expect(result, {'id': 'newId', 'foo': 'baz'});

      final stored = await fakeService.getDocument('col/newId');
      expect(stored, {'id': 'newId', 'foo': 'baz'});
    });

    /// Verifies that getDocument returns the correct document or null.
    test('getDocument returns the correct document or null', () async {
      // Arrange: Create a document.
      await fakeService.createDocument('col', {'id': 'doc1', 'foo': 'bar'});

      // Act: Try to get the existing document and a missing one.
      final found = await fakeService.getDocument('col/doc1');
      final missing = await fakeService.getDocument('col/missing');

      // Assert: The found document should match, missing should be null.
      expect(found, {'id': 'doc1', 'foo': 'bar'});
      expect(missing, isNull);
    });

    /// Verifies that updateDocument actually updates the document.
    test('updateDocument actually updates the document', () async {
      // Arrange: Create a document.
      await fakeService.createDocument('col', {'id': 'doc2', 'foo': 'old'});

      // Act: Update the document.
      final updated = await fakeService.updateDocument('col/doc2', {'id': 'doc2', 'foo': 'updated'});

      // Assert: The returned and stored document should be updated.
      expect(updated, {'id': 'doc2', 'foo': 'updated'});
      final stored = await fakeService.getDocument('col/doc2');
      expect(stored, {'id': 'doc2', 'foo': 'updated'});
    });

    /// Verifies that deleteDocument actually removes the document.
    test('deleteDocument actually removes the document', () async {
      // Arrange: Create a document.
      await fakeService.createDocument('col', {'id': 'doc3', 'foo': 'bar'});

      // Act: Delete the document.
      await fakeService.deleteDocument('col/doc3');

      // Assert: The document should no longer exist.
      final deleted = await fakeService.getDocument('col/doc3');
      expect(deleted, isNull);
    });

    /// Verifies that query returns all documents in the collection.
    test('query returns all documents in the collection', () async {
      // Arrange: Create documents in two collections.
      await fakeService.createDocument('col', {'id': 'a', 'x': 1});
      await fakeService.createDocument('col', {'id': 'b', 'x': 2});
      await fakeService.createDocument('other', {'id': 'c', 'x': 3});

      // Act: Query the 'col' collection.
      final results = await fakeService.query(collection: 'col');

      // Assert: Should return only documents from 'col'.
      expect(results, containsAll([
        {'id': 'a', 'x': 1},
        {'id': 'b', 'x': 2},
      ]));
      expect(results, isNot(contains({'id': 'c', 'x': 3})));
    });

    /// Verifies that batchUpdate actually updates multiple documents.
    test('batchUpdate actually updates documents', () async {
      // Arrange: Create two documents.
      await fakeService.createDocument('col', {'id': 'a', 'foo': 'old'});
      await fakeService.createDocument('col', {'id': 'b', 'bar': 0});

      // Act: Batch update both documents.
      final updates = [
        {
          'path': 'col/a',
          'data': {'foo': 'A'}
        },
        {
          'path': 'col/b',
          'data': {'bar': 123}
        },
      ];
      await fakeService.batchUpdate(updates);

      // Assert: Both documents should be updated.
      final docA = await fakeService.getDocument('col/a');
      final docB = await fakeService.getDocument('col/b');
      expect(docA, {'id': 'a', 'foo': 'A'});
      expect(docB, {'id': 'b', 'bar': 123});
    });
  });
}