/// This file contains widget tests for the Energy Tracking feature's core CRUD (Create, Read, Update, Delete)
/// functionality. It ensures that energy entries can be managed correctly through interactions
/// with the underlying services.
///
/// # How these tests work
/// - The tests use `flutter_test` and `mockito` to simulate user interactions and
///   mock backend services (AuthService and DatabaseService).
/// - `ProviderScope` is used to override providers with mock implementations,
///   allowing for isolated testing of the UI and business logic related to data operations.
/// - User actions like tapping buttons, entering text, and navigating screens are
///   simulated using `WidgetTester` to trigger the CRUD operations.
/// - `verify` is used to ensure that the correct service methods (e.g., `createDocument`,
///   `updateDocument`, `deleteDocument`, `query`) are called with the expected arguments.
/// - `expect` is used to assert the state of the UI where it reflects the outcome of
///   CRUD operations (e.g., an entry appearing or disappearing).
///
/// # Mocking Strategy
/// - `FakeAuthService`: A simple mock implementing `AuthService` to simulate an
///   authenticated user state, necessary for features requiring user authentication.
/// - `MockDatabaseService`: Generated by Mockito, used to stub database operations
///   and verify interactions, forming the core of these CRUD tests.
///
/// # How to run
/// - Run with `flutter test test/features/tracker/crud/energy_crud_redefined.dart`
/// - No external dependencies or network required as services are mocked.

import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:spiceease/core/auth/auth_service.dart';
import 'package:spiceease/core/auth/auth_user_model.dart';
import 'package:spiceease/core/database/database_provider.dart';
import 'package:spiceease/core/auth/auth_provider.dart';
import 'package:spiceease/main.dart'; // Assuming MyApp is your root widget
import 'package:spiceease/core/database/database_service.dart';
import 'package:spiceease/data/models/energy_model.dart'; // For ListModal<EnergyModel>
import 'package:spiceease/features/tracker/presentation/widgets/modals.dart'; // For EnergyLevelEditorModal
import 'package:spiceease/features/tracker/presentation/widgets/list_modal.dart'; // For ListModal

import '../ui/modals/mood_modals_ui_test.mocks.dart';

/// A fake implementation of [AuthService] for testing purposes.
/// It simulates an authenticated user by default.
class FakeAuthService extends Mock implements AuthService {
  @override
  Future<void> initialize() async {}

  @override
  Stream<AppUser?> authStateChanges() =>
      Stream.value(AppUser(uid: 'test-user', email: 'test@example.com'));

  @override
  Future<bool> isSignedIn() async => true;

  @override
  Future<AppUser?> getCurrentUser() async =>
      AppUser(uid: 'test-user', email: 'test@example.com');

  @override
  Future<bool> validateSession() async => true;

  @override
  Future<void> signOut() async {}
}

@GenerateMocks([DatabaseService])
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  late MockDatabaseService mockDatabaseService;
  late FakeAuthService fakeAuthService;
  late List<Override> testProviderOverrides;
  const String energyEntriesCollectionName = 'energy_entries';
  final testDate = DateTime(2025, 5, 30);
  bool _energyItemShouldExistInQuery = true;
  final initialEnergyEntryMap = {
    // Define it once
    'id': 'test-id',
    'energy_level': 7,
    'notes': 'Initial test energy entry',
    'user_id': 'test-user',
    'created_at': testDate.toUtc(),
    'updated_at': testDate.toUtc(),
  };

  setUp(() {
    mockDatabaseService = MockDatabaseService();
    fakeAuthService = FakeAuthService();
    _energyItemShouldExistInQuery = true;

    testProviderOverrides = [
      databaseServiceProvider.overrideWithValue(mockDatabaseService),
      authServiceProvider.overrideWithValue(fakeAuthService),
    ];

    when(mockDatabaseService.generateId()).thenReturn('new-generated-id');

    // Default success stub for creating an energy document
    when(mockDatabaseService.createDocument(
      energyEntriesCollectionName,
      any, // Keep it general for success cases
    )).thenAnswer((invocation) async {
      final Map<String, dynamic> data =
          invocation.positionalArguments[1] as Map<String, dynamic>;
      _energyItemShouldExistInQuery = true;
      return Future.value(data);
    });

    // Default success stub for updating an energy document
    when(mockDatabaseService.updateDocument(
      argThat(startsWith('$energyEntriesCollectionName/test-id')),
      any,
    )).thenAnswer((invocation) async {
      final Map<String, dynamic> data =
          invocation.positionalArguments[1] as Map<String, dynamic>;
      return Future.value({
        ...initialEnergyEntryMap, // Base
        ...data, // Apply updates
        'updated_at': DateTime.now().toUtc(),
      });
    });

    // Default success stub for deleting an energy document
    when(mockDatabaseService
            .deleteDocument('$energyEntriesCollectionName/test-id'))
        .thenAnswer((_) async {
      print(
          "TEST_DEBUG: MOCK deleteDocument executed. Setting _energyItemShouldExistInQuery to false.");
      _energyItemShouldExistInQuery = false;
    });

    // Stateful query mock for energy entries
    when(mockDatabaseService.query(
      collection: energyEntriesCollectionName,
      filters: anyNamed('filters'),
      orderBy: anyNamed('orderBy'),
      limit: anyNamed('limit'),
      startAfter: anyNamed('startAfter'),
      endBefore: anyNamed('endBefore'),
    )).thenAnswer((invocation) async {
      if (!_energyItemShouldExistInQuery) {
        print(
            "TEST_DEBUG: MOCK QUERY for $energyEntriesCollectionName (item set to not exist) - Returning []");
        return [];
      } else {
        print(
            "TEST_DEBUG: MOCK QUERY for $energyEntriesCollectionName (item set to exist) - Returning 1 item");
        return [initialEnergyEntryMap];
      }
    });

    final collectionsToStub = [
      'medications',
      'tasks',
      'recipes',
      'mood_entries',
      'symptoms',
      'habits'
    ];
    for (var collectionName in collectionsToStub) {
      when(mockDatabaseService.query(
        collection: collectionName,
        filters: anyNamed('filters'),
        orderBy: anyNamed('orderBy'),
        limit: anyNamed('limit'),
        startAfter: anyNamed('startAfter'),
        endBefore: anyNamed('endBefore'),
      )).thenAnswer((_) async => []);
    }
  });

  group('Add Energy Entry', () {
    testWidgets('should add a new energy entry when valid data is provided',
        (WidgetTester tester) async {
      _energyItemShouldExistInQuery = false;

      // Specific mock for successful creation in this test
      when(mockDatabaseService.createDocument(
        energyEntriesCollectionName,
        argThat(isA<Map<String, dynamic>>()
            .having((map) => map['id'], 'id', 'new-generated-id')
            .having((map) => map['energy_level'], 'energy_level', 8)
            .having((map) => map['notes'], 'notes', 'High energy today!')
            .having((map) => map['user_id'], 'user_id', 'test-user')),
      )).thenAnswer((invocation) async {
        final Map<String, dynamic> data =
            invocation.positionalArguments[1] as Map<String, dynamic>;
        _energyItemShouldExistInQuery = true;
        return Future.value(data);
      });

      await tester.pumpWidget(
        ProviderScope(overrides: testProviderOverrides, child: const MyApp()),
      );
      await tester.pumpAndSettle();

      final energyIconFinder = find.byIcon(FontAwesomeIcons.bolt);
      await tester.tap(energyIconFinder);
      await tester.pumpAndSettle(); // Opens EnergyLevelEditorModal

      // Find and tap energy level 8
      final energyContainers = find.byType(InkWell);
      expect(energyContainers, findsWidgets);

      // Tap the 8th energy level (index 7 since it's 0-based)
      await tester.tap(energyContainers.at(7));
      await tester.pumpAndSettle();

      final notesFieldFinder = find.byType(TextField).last;
      expect(notesFieldFinder, findsOneWidget);
      await tester.enterText(notesFieldFinder, 'High energy today!');
      await tester.pumpAndSettle();

      final saveButtonFinder = find.text('Save');
      expect(saveButtonFinder, findsOneWidget);
      await tester.tap(saveButtonFinder);
      await tester.pumpAndSettle();

      verify(mockDatabaseService.createDocument(
        energyEntriesCollectionName,
        any, // Already verified by the specific when()
      )).called(1);
      expect(_energyItemShouldExistInQuery, isTrue,
          reason: "Item should exist after creation for subsequent queries.");
      expect(find.byType(EnergyLevelEditorModal), findsNothing,
          reason: "Modal should close on successful save.");
    });

    testWidgets('handles createDocument failure by keeping modal open',
        (WidgetTester tester) async {
      _energyItemShouldExistInQuery = false;

      // Mock createDocument to throw an exception
      when(mockDatabaseService.createDocument(energyEntriesCollectionName, any))
          .thenThrow(Exception('Network error'));

      await tester.pumpWidget(
        ProviderScope(overrides: testProviderOverrides, child: const MyApp()),
      );
      await tester.pumpAndSettle();

      final energyIconFinder = find.byIcon(FontAwesomeIcons.bolt);
      await tester.tap(energyIconFinder);
      await tester.pumpAndSettle(); // Opens EnergyLevelEditorModal

      // Tap energy level 6
      final energyContainers = find.byType(InkWell);
      await tester.tap(energyContainers.at(5)); // 6th level (index 5)
      await tester.enterText(find.byType(TextField).last, 'Will fail to save');
      await tester.pumpAndSettle();

      await tester.tap(find.text('Save'));
      await tester.pumpAndSettle(); // Attempt to save

      // Verify createDocument was called
      verify(mockDatabaseService.createDocument(
              energyEntriesCollectionName, any))
          .called(1);
      // Modal should still be open
      expect(find.byType(EnergyLevelEditorModal), findsOneWidget,
          reason: "Modal should remain open on save failure.");
      // Detailed SnackBar/error message tests are in energy_modals_ui_test.dart
    });
  });

  group('Edit Energy Entry', () {
    testWidgets('should update an existing energy entry when data is modified',
        (WidgetTester tester) async {
      _energyItemShouldExistInQuery = true;

      await tester.pumpWidget(
        ProviderScope(overrides: testProviderOverrides, child: const MyApp()),
      );
      await tester.pumpAndSettle();

      final energyIconFinder = find.byIcon(FontAwesomeIcons.bolt);
      await tester.tap(energyIconFinder);
      await tester.pumpAndSettle(); // Opens ListModal

      expect(find.textContaining('Initial test energy entry'), findsOneWidget);

      final editButtonFinder = find.byIcon(Icons.edit_outlined).first;
      await tester.tap(editButtonFinder);
      await tester.pumpAndSettle(); // Opens EnergyLevelEditorModal

      final notesFieldFinder = find.byType(TextField).last;
      await tester.enterText(notesFieldFinder, 'Edited energy entry notes');
      await tester.pumpAndSettle();

      final saveButtonFinder = find.text('Save');
      await tester.tap(saveButtonFinder);
      await tester.pumpAndSettle();

      verify(mockDatabaseService.updateDocument(
        argThat(startsWith('$energyEntriesCollectionName/test-id')),
        argThat(isA<Map<String, dynamic>>()
            .having((map) => map['id'], 'id', 'test-id')
            .having((map) => map['user_id'], 'user_id', 'test-user')
            .having((map) => map['notes'], 'notes', 'Edited energy entry notes')
            .having((map) => map.containsKey('created_at'), 'created_at', true)
            .having(
                (map) => map.containsKey('updated_at'), 'updated_at', true)),
      )).called(1);
      expect(find.byType(EnergyLevelEditorModal), findsNothing,
          reason: "Modal should close on successful update.");
    });

    testWidgets('handles updateDocument failure by keeping modal open',
        (WidgetTester tester) async {
      _energyItemShouldExistInQuery = true;

      // Mock updateDocument to throw an exception
      when(mockDatabaseService.updateDocument(
              argThat(startsWith('$energyEntriesCollectionName/test-id')), any))
          .thenThrow(Exception('Update failed'));

      await tester.pumpWidget(
        ProviderScope(overrides: testProviderOverrides, child: const MyApp()),
      );
      await tester.pumpAndSettle();

      final energyIconFinder = find.byIcon(FontAwesomeIcons.bolt);
      await tester.tap(energyIconFinder);
      await tester.pumpAndSettle();

      await tester.tap(find.byIcon(Icons.edit_outlined).first);
      await tester.pumpAndSettle();

      await tester.enterText(find.byType(TextField).last, 'Attempting update');
      await tester.pumpAndSettle();

      await tester.tap(find.text('Save'));
      await tester.pumpAndSettle();

      verify(mockDatabaseService.updateDocument(
              argThat(startsWith('$energyEntriesCollectionName/test-id')), any))
          .called(1);
      expect(find.byType(EnergyLevelEditorModal), findsOneWidget,
          reason: "Modal should remain open on update failure.");
    });
  });

  group('Delete Energy Entry', () {
    testWidgets('should delete an existing energy entry after confirmation',
        (WidgetTester tester) async {
      _energyItemShouldExistInQuery = true;

      await tester.pumpWidget(
        ProviderScope(overrides: testProviderOverrides, child: const MyApp()),
      );
      await tester.pumpAndSettle();
      print(
          "TEST_DEBUG: App pumped and settled. _energyItemShouldExistInQuery: $_energyItemShouldExistInQuery");

      final energyIconFinder = find.byIcon(FontAwesomeIcons.bolt);
      expect(energyIconFinder, findsOneWidget,
          reason: "Energy icon should be on home screen.");

      print("TEST_DEBUG: Tapping energy icon (1st time) to open ListModal.");
      await tester.tap(energyIconFinder);
      await tester.pumpAndSettle();
      print("TEST_DEBUG: pumpAndSettle after 1st energy icon tap.");

      expect(find.byType(ListModal<EnergyModel>), findsOneWidget,
          reason: "ListModal should be open with the item.");
      expect(find.textContaining('Initial test energy entry'), findsOneWidget,
          reason: "Entry text should be in ListModal.");

      final deleteButtonFinder = find
          .descendant(
              of: find.byType(ListModal<EnergyModel>),
              matching: find.byIcon(Icons.delete_outline))
          .first;
      expect(deleteButtonFinder, findsOneWidget,
          reason: "Delete button should be in ListModal.");

      print("TEST_DEBUG: Tapping delete button in ListModal.");
      await tester.tap(deleteButtonFinder);
      await tester.pumpAndSettle();
      print(
          "TEST_DEBUG: pumpAndSettle after tapping delete icon (confirmation dialog should appear).");

      final confirmDeleteFinder = find.widgetWithText(TextButton, 'Delete');
      expect(confirmDeleteFinder, findsOneWidget,
          reason: "Confirmation 'Delete' button should be present.");

      print(
          "TEST_DEBUG: Tapping 'Delete' on confirmation dialog. This will trigger mock deleteDocument.");
      await tester.tap(confirmDeleteFinder);
      // The mock deleteDocument has now set _energyItemShouldExistInQuery to false.

      print(
          "TEST_DEBUG: pumpAndSettle after tapping confirm delete. _energyItemShouldExistInQuery is now $_energyItemShouldExistInQuery");
      await tester.pumpAndSettle(const Duration(milliseconds: 500));

      print("TEST_DEBUG: Checking if ListModal is gone.");
      // If ListModal closes when empty, this is correct.
      // If it stays open to show an empty message, this expectation would change.
      // Based on previous behavior, assuming it closes/navigates away when empty.
      expect(find.byType(ListModal<EnergyModel>), findsNothing,
          reason:
              "ListModal should be gone after item deletion and refresh, assuming it pops when empty or navigates to editor.");

      print("TEST_DEBUG: Checking if item text is gone from screen.");
      expect(find.textContaining('Initial test energy entry'), findsNothing,
          reason: "Entry text should not be on screen.");

      print(
          "TEST_DEBUG: Tapping energy icon (2nd time) - IconListLauncher should now know list is empty.");
      await tester.tap(energyIconFinder);
      await tester.pumpAndSettle(const Duration(milliseconds: 500));
      print(
          "TEST_DEBUG: pumpAndSettle after 2nd energy icon tap (EnergyLevelEditorModal should appear).");

      expect(find.byType(EnergyLevelEditorModal), findsOneWidget,
          reason:
              "EnergyLevelEditorModal should open as the list is now empty.");
      expect(find.byType(ListModal<EnergyModel>), findsNothing,
          reason:
              "ListModal should NOT be open when EnergyLevelEditorModal is shown.");

      verify(mockDatabaseService
              .deleteDocument('$energyEntriesCollectionName/test-id'))
          .called(1);
      verify(mockDatabaseService.query(
        collection: energyEntriesCollectionName,
        filters: anyNamed('filters'),
        orderBy: anyNamed('orderBy'),
        limit: anyNamed('limit'),
        startAfter: anyNamed('startAfter'),
        endBefore: anyNamed('endBefore'),
      )).called(greaterThanOrEqualTo(2));
    });

    testWidgets(
        'handles deleteDocument failure by keeping ListModal open with item',
        (WidgetTester tester) async {
      _energyItemShouldExistInQuery = true;

      // Mock deleteDocument to throw an exception
      when(mockDatabaseService
              .deleteDocument('$energyEntriesCollectionName/test-id'))
          .thenThrow(Exception('Deletion failed'));

      await tester.pumpWidget(
        ProviderScope(overrides: testProviderOverrides, child: const MyApp()),
      );
      await tester.pumpAndSettle();

      final energyIconFinder = find.byIcon(FontAwesomeIcons.bolt);
      await tester.tap(energyIconFinder);
      await tester.pumpAndSettle();

      await tester.tap(find.byIcon(Icons.delete_outline).first);
      await tester.pumpAndSettle();

      await tester.tap(find.widgetWithText(TextButton, 'Delete'));
      await tester.pumpAndSettle();

      verify(mockDatabaseService
              .deleteDocument('$energyEntriesCollectionName/test-id'))
          .called(1);
      // Confirmation dialog might close, but ListModal should remain and still show the item.
      expect(find.byType(ListModal<EnergyModel>), findsOneWidget,
          reason: "ListModal should remain if delete failed.");
      expect(find.textContaining('Initial test energy entry'), findsOneWidget,
          reason: "Item should still be listed on delete failure.");

      // Ensure our state variable reflects that the item wasn't "deleted" for subsequent query mocks
      _energyItemShouldExistInQuery = true;
    });
  });

  group('View Energy Entry', () {
    testWidgets('should display existing energy entries on the list screen',
        (WidgetTester tester) async {
      _energyItemShouldExistInQuery = true;

      await tester.pumpWidget(
        ProviderScope(overrides: testProviderOverrides, child: const MyApp()),
      );
      await tester.pumpAndSettle();

      final energyIconFinder = find.byIcon(FontAwesomeIcons.bolt);
      await tester.tap(energyIconFinder);
      await tester.pumpAndSettle();

      expect(find.textContaining('Initial test energy entry'), findsOneWidget);

      verify(mockDatabaseService.query(
        collection: energyEntriesCollectionName,
        filters: anyNamed('filters'),
        orderBy: anyNamed('orderBy'),
        limit: anyNamed('limit'),
        startAfter: anyNamed('startAfter'),
        endBefore: anyNamed('endBefore'),
      )).called(greaterThanOrEqualTo(1));
    });
  });

  group('Energy Level Selection', () {
    testWidgets('should allow selecting different energy levels',
        (WidgetTester tester) async {
      _energyItemShouldExistInQuery = false;

      await tester.pumpWidget(
        ProviderScope(overrides: testProviderOverrides, child: const MyApp()),
      );
      await tester.pumpAndSettle();

      final energyIconFinder = find.byIcon(FontAwesomeIcons.bolt);
      await tester.tap(energyIconFinder);
      await tester.pumpAndSettle(); // Opens EnergyLevelEditorModal

      // Test selecting different energy levels
      final energyContainers = find.byType(InkWell);
      expect(
          energyContainers, findsNWidgets(10)); // Should have 10 energy levels

      // Test clicking on energy level 3
      await tester.tap(energyContainers.at(2)); // 3rd level (index 2)
      await tester.pumpAndSettle();

      // Test clicking on energy level 9
      await tester.tap(energyContainers.at(8)); // 9th level (index 8)
      await tester.pumpAndSettle();

      // Verify the modal is still open and functional
      expect(find.byType(EnergyLevelEditorModal), findsOneWidget);
      expect(find.text('Save'), findsOneWidget);
      expect(find.text('Cancel'), findsOneWidget);
    });

    testWidgets('should show validation error when no energy level is selected',
        (WidgetTester tester) async {
      _energyItemShouldExistInQuery = false;

      await tester.pumpWidget(
        ProviderScope(overrides: testProviderOverrides, child: const MyApp()),
      );
      await tester.pumpAndSettle();

      final energyIconFinder = find.byIcon(FontAwesomeIcons.bolt);
      await tester.tap(energyIconFinder);
      await tester.pumpAndSettle(); // Opens EnergyLevelEditorModal

      // Try to save without selecting an energy level
      final saveButtonFinder = find.text('Save');
      await tester.tap(saveButtonFinder);
      await tester.pumpAndSettle();

      // Should show validation error and keep modal open
      expect(find.byType(EnergyLevelEditorModal), findsOneWidget,
          reason: "Modal should remain open when validation fails.");

      // Should show a SnackBar with error message
      expect(find.byType(SnackBar), findsOneWidget);
    });
  });

  group('Energy Notes', () {
    testWidgets('should save energy entry with notes',
        (WidgetTester tester) async {
      _energyItemShouldExistInQuery = false;

      when(mockDatabaseService.createDocument(
        energyEntriesCollectionName,
        argThat(isA<Map<String, dynamic>>()
            .having((map) => map['energy_level'], 'energy_level', 5)
            .having(
                (map) => map['notes'], 'notes', 'Moderate energy with coffee')),
      )).thenAnswer((invocation) async {
        final Map<String, dynamic> data =
            invocation.positionalArguments[1] as Map<String, dynamic>;
        _energyItemShouldExistInQuery = true;
        return Future.value(data);
      });

      await tester.pumpWidget(
        ProviderScope(overrides: testProviderOverrides, child: const MyApp()),
      );
      await tester.pumpAndSettle();

      final energyIconFinder = find.byIcon(FontAwesomeIcons.bolt);
      await tester.tap(energyIconFinder);
      await tester.pumpAndSettle();

      // Select energy level 5
      final energyContainers = find.byType(InkWell);
      await tester.tap(energyContainers.at(4)); // 5th level (index 4)
      await tester.pumpAndSettle();

      // Add notes
      final notesFieldFinder = find.byType(TextField);
      expect(notesFieldFinder, findsOneWidget);
      await tester.enterText(notesFieldFinder, 'Moderate energy with coffee');
      await tester.pumpAndSettle();

      // Save
      await tester.tap(find.text('Save'));
      await tester.pumpAndSettle();

      verify(mockDatabaseService.createDocument(
        energyEntriesCollectionName,
        any,
      )).called(1);
    });

    testWidgets('should save energy entry without notes',
        (WidgetTester tester) async {
      _energyItemShouldExistInQuery = false;

      when(mockDatabaseService.createDocument(
        energyEntriesCollectionName,
        argThat(isA<Map<String, dynamic>>()
            .having((map) => map['energy_level'], 'energy_level', 10)
            .having((map) => map['notes'], 'notes', '')),
      )).thenAnswer((invocation) async {
        final Map<String, dynamic> data =
            invocation.positionalArguments[1] as Map<String, dynamic>;
        _energyItemShouldExistInQuery = true;
        return Future.value(data);
      });

      await tester.pumpWidget(
        ProviderScope(overrides: testProviderOverrides, child: const MyApp()),
      );
      await tester.pumpAndSettle();

      final energyIconFinder = find.byIcon(FontAwesomeIcons.bolt);
      await tester.tap(energyIconFinder);
      await tester.pumpAndSettle();

      // Select maximum energy level (10)
      final energyContainers = find.byType(InkWell);
      await tester.tap(energyContainers.at(9)); // 10th level (index 9)
      await tester.pumpAndSettle();

      // Don't add notes, save directly
      await tester.tap(find.text('Save'));
      await tester.pumpAndSettle();

      verify(mockDatabaseService.createDocument(
        energyEntriesCollectionName,
        any,
      )).called(1);
    });
  });
}
