/// This file contains widget tests for the Mood Tracking feature's core CRUD (Create, Read, Update, Delete)
/// functionality. It ensures that mood entries can be managed correctly through interactions
/// with the underlying services.
///
/// # How these tests work
/// - The tests use `flutter_test` and `mockito` to simulate user interactions and
///   mock backend services (AuthService and DatabaseService).
/// - `ProviderScope` is used to override providers with mock implementations,
///   allowing for isolated testing of the UI and business logic related to data operations.
/// - User actions like tapping buttons, entering text, and navigating screens are
///   simulated using `WidgetTester` to trigger the CRUD operations.
/// - `verify` is used to ensure that the correct service methods (e.g., `createDocument`,
///   `updateDocument`, `deleteDocument`, `query`) are called with the expected arguments.
/// - `expect` is used to assert the state of the UI where it reflects the outcome of
///   CRUD operations (e.g., an entry appearing or disappearing).
///
/// # Mocking Strategy
/// - `FakeAuthService`: A simple mock implementing `AuthService` to simulate an
///   authenticated user state, necessary for features requiring user authentication.
/// - `MockDatabaseService`: Generated by Mockito, used to stub database operations
///   and verify interactions, forming the core of these CRUD tests.
///
/// # How to run
/// - Run with `flutter test test/features/tracker/mood_crud_redefined.dart`
/// - No external dependencies or network required as services are mocked.

import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:spiceease/core/auth/auth_service.dart';
import 'package:spiceease/core/auth/auth_user_model.dart';
import 'package:spiceease/core/database/database_provider.dart';
import 'package:spiceease/core/auth/auth_provider.dart';
import 'package:spiceease/main.dart'; // Assuming MyApp is your root widget
import 'package:spiceease/core/database/database_service.dart';
import 'package:spiceease/data/models/mood_model.dart'; // For ListModal<MoodModel>
import 'package:spiceease/features/tracker/presentation/widgets/modals.dart'; // For MoodLevelEditorModal
import 'package:spiceease/features/tracker/presentation/widgets/list_modal.dart'; // For ListModal

import '../tracker_mood_test.mocks.dart';

/// A fake implementation of [AuthService] for testing purposes.
/// It simulates an authenticated user by default.
class FakeAuthService extends Mock implements AuthService {
  @override
  Future<void> initialize() async {}

  @override
  Stream<AppUser?> authStateChanges() =>
      Stream.value(AppUser(uid: 'test-user', email: 'test@example.com'));

  @override
  Future<bool> isSignedIn() async => true;

  @override
  Future<AppUser?> getCurrentUser() async =>
      AppUser(uid: 'test-user', email: 'test@example.com');

  @override
  Future<bool> validateSession() async => true;

  @override
  Future<void> signOut() async {}
}

@GenerateMocks([DatabaseService])
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  late MockDatabaseService mockDatabaseService;
  late FakeAuthService fakeAuthService;
  late List<Override> testProviderOverrides;
  const String moodEntriesCollectionName = 'mood_entries';
  final testDate = DateTime(2025, 5, 30);
  bool _moodItemShouldExistInQuery = true;
  final initialMoodEntryMap = {
    // Define it once
    'id': 'test-id',
    'mood_level': 5,
    'notes': 'Initial test mood entry',
    'user_id': 'test-user',
    'created_at': testDate.toUtc(),
    'updated_at': testDate.toUtc(),
  };

  setUp(() {
    mockDatabaseService = MockDatabaseService();
    fakeAuthService = FakeAuthService();
    _moodItemShouldExistInQuery = true;

    testProviderOverrides = [
      databaseServiceProvider.overrideWithValue(mockDatabaseService),
      authServiceProvider.overrideWithValue(fakeAuthService),
    ];

    when(mockDatabaseService.generateId()).thenReturn('new-generated-id');

    // Default success stub for creating a mood document
    when(mockDatabaseService.createDocument(
      moodEntriesCollectionName,
      any, // Keep it general for success cases
    )).thenAnswer((invocation) async {
      final Map<String, dynamic> data =
          invocation.positionalArguments[1] as Map<String, dynamic>;
      _moodItemShouldExistInQuery = true;
      return Future.value(data);
    });

    // Default success stub for updating a mood document
    when(mockDatabaseService.updateDocument(
      argThat(startsWith('$moodEntriesCollectionName/test-id')),
      any,
    )).thenAnswer((invocation) async {
      final Map<String, dynamic> data =
          invocation.positionalArguments[1] as Map<String, dynamic>;
      return Future.value({
        ...initialMoodEntryMap, // Base
        ...data, // Apply updates
        'updated_at': DateTime.now().toUtc(),
      });
    });

    // Default success stub for deleting a mood document
    when(mockDatabaseService
            .deleteDocument('$moodEntriesCollectionName/test-id'))
        .thenAnswer((_) async {
      print(
          "TEST_DEBUG: MOCK deleteDocument executed. Setting _moodItemShouldExistInQuery to false.");
      _moodItemShouldExistInQuery = false;
    });

    // Stateful query mock for mood entries
    when(mockDatabaseService.query(
      collection: moodEntriesCollectionName,
      filters: anyNamed('filters'),
      orderBy: anyNamed('orderBy'),
      limit: anyNamed('limit'),
      startAfter: anyNamed('startAfter'),
      endBefore: anyNamed('endBefore'),
    )).thenAnswer((invocation) async {
      if (!_moodItemShouldExistInQuery) {
        print(
            "TEST_DEBUG: MOCK QUERY for $moodEntriesCollectionName (item set to not exist) - Returning []");
        return [];
      } else {
        print(
            "TEST_DEBUG: MOCK QUERY for $moodEntriesCollectionName (item set to exist) - Returning 1 item");
        return [initialMoodEntryMap];
      }
    });

    final collectionsToStub = [
      'medications',
      'tasks',
      'recipes',
      'energy_entries',
      'symptoms',
      'habits'
    ];
    for (var collectionName in collectionsToStub) {
      when(mockDatabaseService.query(
        collection: collectionName,
        filters: anyNamed('filters'),
        orderBy: anyNamed('orderBy'),
        limit: anyNamed('limit'),
        startAfter: anyNamed('startAfter'),
        endBefore: anyNamed('endBefore'),
      )).thenAnswer((_) async => []);
    }
  });

  group('Add Mood Entry', () {
    testWidgets('should add a new mood entry when valid data is provided',
        (WidgetTester tester) async {
      _moodItemShouldExistInQuery = false;

      // Specific mock for successful creation in this test
      when(mockDatabaseService.createDocument(
        moodEntriesCollectionName,
        argThat(isA<Map<String, dynamic>>()
            .having((map) => map['id'], 'id', 'new-generated-id')
            .having((map) => map['mood_level'], 'mood_level', 5)
            .having((map) => map['notes'], 'notes', 'Feeling great today!')
            .having((map) => map['user_id'], 'user_id', 'test-user')),
      )).thenAnswer((invocation) async {
        final Map<String, dynamic> data =
            invocation.positionalArguments[1] as Map<String, dynamic>;
        _moodItemShouldExistInQuery = true;
        return Future.value(data);
      });

      await tester.pumpWidget(
        ProviderScope(overrides: testProviderOverrides, child: const MyApp()),
      );
      await tester.pumpAndSettle();

      final moodIconFinder = find.byIcon(FontAwesomeIcons.faceSmile);
      await tester.tap(moodIconFinder);
      await tester.pumpAndSettle(); // Opens MoodLevelEditorModal

      final moodValueFinder = find.byKey(const ValueKey('moodValue_5'));
      expect(moodValueFinder, findsOneWidget);
      await tester.tap(moodValueFinder);
      await tester.pumpAndSettle();

      final notesFieldFinder = find.byType(TextField).last;
      expect(notesFieldFinder, findsOneWidget);
      await tester.enterText(notesFieldFinder, 'Feeling great today!');
      await tester.pumpAndSettle();

      final saveButtonFinder = find.text('Save');
      expect(saveButtonFinder, findsOneWidget);
      await tester.tap(saveButtonFinder);
      await tester.pumpAndSettle();

      verify(mockDatabaseService.createDocument(
        moodEntriesCollectionName,
        any, // Already verified by the specific when()
      )).called(1);
      expect(_moodItemShouldExistInQuery, isTrue,
          reason: "Item should exist after creation for subsequent queries.");
      expect(find.byType(MoodLevelEditorModal), findsNothing,
          reason: "Modal should close on successful save.");
    });

    testWidgets('handles createDocument failure by keeping modal open',
        (WidgetTester tester) async {
      _moodItemShouldExistInQuery = false;

      // Mock createDocument to throw an exception
      when(mockDatabaseService.createDocument(moodEntriesCollectionName, any))
          .thenThrow(Exception('Network error'));

      await tester.pumpWidget(
        ProviderScope(overrides: testProviderOverrides, child: const MyApp()),
      );
      await tester.pumpAndSettle();

      final moodIconFinder = find.byIcon(FontAwesomeIcons.faceSmile);
      await tester.tap(moodIconFinder);
      await tester.pumpAndSettle(); // Opens MoodLevelEditorModal

      await tester.tap(find.byKey(const ValueKey('moodValue_5')));
      await tester.enterText(find.byType(TextField).last, 'Will fail to save');
      await tester.pumpAndSettle();

      await tester.tap(find.text('Save'));
      await tester.pumpAndSettle(); // Attempt to save

      // Verify createDocument was called
      verify(mockDatabaseService.createDocument(moodEntriesCollectionName, any))
          .called(1);
      // Modal should still be open
      expect(find.byType(MoodLevelEditorModal), findsOneWidget,
          reason: "Modal should remain open on save failure.");
      // Detailed SnackBar/error message tests are in mood_modals_ui_test.dart
    });
  });

  group('Edit Mood Entry', () {
    testWidgets('should update an existing mood entry when data is modified',
        (WidgetTester tester) async {
      _moodItemShouldExistInQuery = true;

      await tester.pumpWidget(
        ProviderScope(overrides: testProviderOverrides, child: const MyApp()),
      );
      await tester.pumpAndSettle();

      final moodIconFinder = find.byIcon(FontAwesomeIcons.faceSmile);
      await tester.tap(moodIconFinder);
      await tester.pumpAndSettle(); // Opens ListModal

      expect(find.textContaining('Initial test mood entry'), findsOneWidget);

      final editButtonFinder = find.byIcon(Icons.edit_outlined).first;
      await tester.tap(editButtonFinder);
      await tester.pumpAndSettle(); // Opens MoodLevelEditorModal

      final notesFieldFinder = find.byType(TextField).last;
      await tester.enterText(notesFieldFinder, 'Edited mood entry notes');
      await tester.pumpAndSettle();

      final saveButtonFinder = find.text('Save');
      await tester.tap(saveButtonFinder);
      await tester.pumpAndSettle();

      verify(mockDatabaseService.updateDocument(
        argThat(startsWith('$moodEntriesCollectionName/test-id')),
        argThat(isA<Map<String, dynamic>>()
            .having((map) => map['id'], 'id', 'test-id')
            .having((map) => map['user_id'], 'user_id', 'test-user')
            .having((map) => map['notes'], 'notes', 'Edited mood entry notes')
            .having((map) => map.containsKey('created_at'), 'created_at', true)
            .having(
                (map) => map.containsKey('updated_at'), 'updated_at', true)),
      )).called(1);
      expect(find.byType(MoodLevelEditorModal), findsNothing,
          reason: "Modal should close on successful update.");
    });

    testWidgets('handles updateDocument failure by keeping modal open',
        (WidgetTester tester) async {
      _moodItemShouldExistInQuery = true;

      // Mock updateDocument to throw an exception
      when(mockDatabaseService.updateDocument(
              argThat(startsWith('$moodEntriesCollectionName/test-id')), any))
          .thenThrow(Exception('Update failed'));

      await tester.pumpWidget(
        ProviderScope(overrides: testProviderOverrides, child: const MyApp()),
      );
      await tester.pumpAndSettle();

      final moodIconFinder = find.byIcon(FontAwesomeIcons.faceSmile);
      await tester.tap(moodIconFinder);
      await tester.pumpAndSettle();

      await tester.tap(find.byIcon(Icons.edit_outlined).first);
      await tester.pumpAndSettle();

      await tester.enterText(find.byType(TextField).last, 'Attempting update');
      await tester.pumpAndSettle();

      await tester.tap(find.text('Save'));
      await tester.pumpAndSettle();

      verify(mockDatabaseService.updateDocument(
              argThat(startsWith('$moodEntriesCollectionName/test-id')), any))
          .called(1);
      expect(find.byType(MoodLevelEditorModal), findsOneWidget,
          reason: "Modal should remain open on update failure.");
    });
  });

  group('Delete Mood Entry', () {
    testWidgets('should delete an existing mood entry after confirmation',
        (WidgetTester tester) async {
      _moodItemShouldExistInQuery = true;

      await tester.pumpWidget(
        ProviderScope(overrides: testProviderOverrides, child: const MyApp()),
      );
      await tester.pumpAndSettle();
      print(
          "TEST_DEBUG: App pumped and settled. _moodItemShouldExistInQuery: $_moodItemShouldExistInQuery");

      final moodIconFinder = find.byIcon(FontAwesomeIcons.faceSmile);
      expect(moodIconFinder, findsOneWidget,
          reason: "Mood icon should be on home screen.");

      print("TEST_DEBUG: Tapping mood icon (1st time) to open ListModal.");
      await tester.tap(moodIconFinder);
      await tester.pumpAndSettle();
      print("TEST_DEBUG: pumpAndSettle after 1st mood icon tap.");

      expect(find.byType(ListModal<MoodModel>), findsOneWidget,
          reason: "ListModal should be open with the item.");
      expect(find.textContaining('Initial test mood entry'), findsOneWidget,
          reason: "Entry text should be in ListModal.");

      final deleteButtonFinder = find
          .descendant(
              of: find.byType(ListModal<MoodModel>),
              matching: find.byIcon(Icons.delete_outline))
          .first;
      expect(deleteButtonFinder, findsOneWidget,
          reason: "Delete button should be in ListModal.");

      print("TEST_DEBUG: Tapping delete button in ListModal.");
      await tester.tap(deleteButtonFinder);
      await tester.pumpAndSettle();
      print(
          "TEST_DEBUG: pumpAndSettle after tapping delete icon (confirmation dialog should appear).");

      final confirmDeleteFinder = find.widgetWithText(TextButton, 'Delete');
      expect(confirmDeleteFinder, findsOneWidget,
          reason: "Confirmation 'Delete' button should be present.");

      print(
          "TEST_DEBUG: Tapping 'Delete' on confirmation dialog. This will trigger mock deleteDocument.");
      await tester.tap(confirmDeleteFinder);
      // The mock deleteDocument has now set _moodItemShouldExistInQuery to false.

      print(
          "TEST_DEBUG: pumpAndSettle after tapping confirm delete. _moodItemShouldExistInQuery is now $_moodItemShouldExistInQuery");
      await tester.pumpAndSettle(const Duration(milliseconds: 500));

      print("TEST_DEBUG: Checking if ListModal is gone.");
      // If ListModal closes when empty, this is correct.
      // If it stays open to show an empty message, this expectation would change.
      // Based on previous behavior, assuming it closes/navigates away when empty.
      expect(find.byType(ListModal<MoodModel>), findsNothing,
          reason:
              "ListModal should be gone after item deletion and refresh, assuming it pops when empty or navigates to editor.");

      print("TEST_DEBUG: Checking if item text is gone from screen.");
      expect(find.textContaining('Initial test mood entry'), findsNothing,
          reason: "Entry text should not be on screen.");

      print(
          "TEST_DEBUG: Tapping mood icon (2nd time) - IconListLauncher should now know list is empty.");
      await tester.tap(moodIconFinder);
      await tester.pumpAndSettle(const Duration(milliseconds: 500));
      print(
          "TEST_DEBUG: pumpAndSettle after 2nd mood icon tap (MoodLevelEditorModal should appear).");

      expect(find.byType(MoodLevelEditorModal), findsOneWidget,
          reason: "MoodLevelEditorModal should open as the list is now empty.");
      expect(find.byType(ListModal<MoodModel>), findsNothing,
          reason:
              "ListModal should NOT be open when MoodLevelEditorModal is shown.");

      verify(mockDatabaseService
              .deleteDocument('$moodEntriesCollectionName/test-id'))
          .called(1);
      verify(mockDatabaseService.query(
        collection: moodEntriesCollectionName,
        filters: anyNamed('filters'),
        orderBy: anyNamed('orderBy'),
        limit: anyNamed('limit'),
        startAfter: anyNamed('startAfter'),
        endBefore: anyNamed('endBefore'),
      )).called(greaterThanOrEqualTo(2));
    });

    testWidgets(
        'handles deleteDocument failure by keeping ListModal open with item',
        (WidgetTester tester) async {
      _moodItemShouldExistInQuery = true;

      // Mock deleteDocument to throw an exception
      when(mockDatabaseService
              .deleteDocument('$moodEntriesCollectionName/test-id'))
          .thenThrow(Exception('Deletion failed'));

      await tester.pumpWidget(
        ProviderScope(overrides: testProviderOverrides, child: const MyApp()),
      );
      await tester.pumpAndSettle();

      final moodIconFinder = find.byIcon(FontAwesomeIcons.faceSmile);
      await tester.tap(moodIconFinder);
      await tester.pumpAndSettle();

      await tester.tap(find.byIcon(Icons.delete_outline).first);
      await tester.pumpAndSettle();

      await tester.tap(find.widgetWithText(TextButton, 'Delete'));
      await tester.pumpAndSettle();

      verify(mockDatabaseService
              .deleteDocument('$moodEntriesCollectionName/test-id'))
          .called(1);
      // Confirmation dialog might close, but ListModal should remain and still show the item.
      expect(find.byType(ListModal<MoodModel>), findsOneWidget,
          reason: "ListModal should remain if delete failed.");
      expect(find.textContaining('Initial test mood entry'), findsOneWidget,
          reason: "Item should still be listed on delete failure.");

      // Ensure our state variable reflects that the item wasn't "deleted" for subsequent query mocks
      _moodItemShouldExistInQuery = true;
    });
  });

  group('View Mood Entry', () {
    testWidgets('should display existing mood entries on the list screen',
        (WidgetTester tester) async {
      _moodItemShouldExistInQuery = true;

      await tester.pumpWidget(
        ProviderScope(overrides: testProviderOverrides, child: const MyApp()),
      );
      await tester.pumpAndSettle();

      final moodIconFinder = find.byIcon(FontAwesomeIcons.faceSmile);
      await tester.tap(moodIconFinder);
      await tester.pumpAndSettle();

      expect(find.textContaining('Initial test mood entry'), findsOneWidget);

      verify(mockDatabaseService.query(
        collection: moodEntriesCollectionName,
        filters: anyNamed('filters'),
        orderBy: anyNamed('orderBy'),
        limit: anyNamed('limit'),
        startAfter: anyNamed('startAfter'),
        endBefore: anyNamed('endBefore'),
      )).called(greaterThanOrEqualTo(1));
    });
  });
}
