// Mocks generated by Mockito 5.4.6 from annotations
// in spiceease/test/features/reports/reports_ui_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:spiceease/data/models/energy_model.dart' as _i7;
import 'package:spiceease/data/models/flowmodoro_model.dart' as _i8;
import 'package:spiceease/data/models/habit_model.dart' as _i5;
import 'package:spiceease/data/models/medication_model.dart' as _i9;
import 'package:spiceease/data/models/mood_model.dart' as _i4;
import 'package:spiceease/data/models/subtask_model.dart' as _i3;
import 'package:spiceease/data/models/symptom_model.dart' as _i6;
import 'package:spiceease/data/models/task_model.dart' as _i2;
import 'package:spiceease/data/services/energy_service.dart' as _i17;
import 'package:spiceease/data/services/flowmodoro_service.dart' as _i18;
import 'package:spiceease/data/services/habit_service.dart' as _i15;
import 'package:spiceease/data/services/medication_service.dart' as _i19;
import 'package:spiceease/data/services/mood_service.dart' as _i14;
import 'package:spiceease/data/services/subtask_service.dart' as _i13;
import 'package:spiceease/data/services/symptom_service.dart' as _i16;
import 'package:spiceease/data/services/task_service.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTaskModel_0 extends _i1.SmartFake implements _i2.TaskModel {
  _FakeTaskModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSubtaskModel_1 extends _i1.SmartFake implements _i3.SubtaskModel {
  _FakeSubtaskModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMoodModel_2 extends _i1.SmartFake implements _i4.MoodModel {
  _FakeMoodModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHabitModel_3 extends _i1.SmartFake implements _i5.HabitModel {
  _FakeHabitModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSymptomModel_4 extends _i1.SmartFake implements _i6.SymptomModel {
  _FakeSymptomModel_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEnergyModel_5 extends _i1.SmartFake implements _i7.EnergyModel {
  _FakeEnergyModel_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlowmodoroModel_6 extends _i1.SmartFake
    implements _i8.FlowmodoroModel {
  _FakeFlowmodoroModel_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMedicationModel_7 extends _i1.SmartFake
    implements _i9.MedicationModel {
  _FakeMedicationModel_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TaskService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskService extends _i1.Mock implements _i10.TaskService {
  MockTaskService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<List<_i2.TaskModel>> getAllTasks() => (super.noSuchMethod(
        Invocation.method(
          #getAllTasks,
          [],
        ),
        returnValue: _i11.Future<List<_i2.TaskModel>>.value(<_i2.TaskModel>[]),
      ) as _i11.Future<List<_i2.TaskModel>>);

  @override
  _i11.Future<_i2.TaskModel?> getTaskById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getTaskById,
          [id],
        ),
        returnValue: _i11.Future<_i2.TaskModel?>.value(),
      ) as _i11.Future<_i2.TaskModel?>);

  @override
  _i11.Future<_i2.TaskModel> createTask(_i2.TaskModel? task) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTask,
          [task],
        ),
        returnValue: _i11.Future<_i2.TaskModel>.value(_FakeTaskModel_0(
          this,
          Invocation.method(
            #createTask,
            [task],
          ),
        )),
      ) as _i11.Future<_i2.TaskModel>);

  @override
  _i11.Future<_i2.TaskModel> updateTask(
    String? id,
    _i2.TaskModel? task,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [
            id,
            task,
          ],
        ),
        returnValue: _i11.Future<_i2.TaskModel>.value(_FakeTaskModel_0(
          this,
          Invocation.method(
            #updateTask,
            [
              id,
              task,
            ],
          ),
        )),
      ) as _i11.Future<_i2.TaskModel>);

  @override
  _i11.Future<void> deleteTask(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<List<_i2.TaskModel>> getTasksForDate(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksForDate,
          [date],
        ),
        returnValue: _i11.Future<List<_i2.TaskModel>>.value(<_i2.TaskModel>[]),
      ) as _i11.Future<List<_i2.TaskModel>>);

  @override
  String generateId() => (super.noSuchMethod(
        Invocation.method(
          #generateId,
          [],
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #generateId,
            [],
          ),
        ),
      ) as String);

  @override
  _i11.Future<String> getCurrentUserId() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserId,
          [],
        ),
        returnValue: _i11.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #getCurrentUserId,
            [],
          ),
        )),
      ) as _i11.Future<String>);

  @override
  _i11.Future<void> toggleTaskCompletion(
    String? taskId,
    DateTime? selectedDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleTaskCompletion,
          [
            taskId,
            selectedDate,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
}

/// A class which mocks [SubtaskService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubtaskService extends _i1.Mock implements _i13.SubtaskService {
  MockSubtaskService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<List<_i3.SubtaskModel>> getAllSubtasks() => (super.noSuchMethod(
        Invocation.method(
          #getAllSubtasks,
          [],
        ),
        returnValue:
            _i11.Future<List<_i3.SubtaskModel>>.value(<_i3.SubtaskModel>[]),
      ) as _i11.Future<List<_i3.SubtaskModel>>);

  @override
  _i11.Future<_i3.SubtaskModel?> getSubtaskById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubtaskById,
          [id],
        ),
        returnValue: _i11.Future<_i3.SubtaskModel?>.value(),
      ) as _i11.Future<_i3.SubtaskModel?>);

  @override
  _i11.Future<_i3.SubtaskModel> createSubtask(_i3.SubtaskModel? subtask) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSubtask,
          [subtask],
        ),
        returnValue: _i11.Future<_i3.SubtaskModel>.value(_FakeSubtaskModel_1(
          this,
          Invocation.method(
            #createSubtask,
            [subtask],
          ),
        )),
      ) as _i11.Future<_i3.SubtaskModel>);

  @override
  _i11.Future<_i3.SubtaskModel> updateSubtask(
    String? id,
    _i3.SubtaskModel? subtask,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSubtask,
          [
            id,
            subtask,
          ],
        ),
        returnValue: _i11.Future<_i3.SubtaskModel>.value(_FakeSubtaskModel_1(
          this,
          Invocation.method(
            #updateSubtask,
            [
              id,
              subtask,
            ],
          ),
        )),
      ) as _i11.Future<_i3.SubtaskModel>);

  @override
  _i11.Future<void> deleteSubtask(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteSubtask,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<List<_i3.SubtaskModel>> getSubtasksForTask(String? taskId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubtasksForTask,
          [taskId],
        ),
        returnValue:
            _i11.Future<List<_i3.SubtaskModel>>.value(<_i3.SubtaskModel>[]),
      ) as _i11.Future<List<_i3.SubtaskModel>>);

  @override
  _i11.Future<_i3.SubtaskModel> createSubtaskAndUpdateParent(
          _i3.SubtaskModel? subtask) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSubtaskAndUpdateParent,
          [subtask],
        ),
        returnValue: _i11.Future<_i3.SubtaskModel>.value(_FakeSubtaskModel_1(
          this,
          Invocation.method(
            #createSubtaskAndUpdateParent,
            [subtask],
          ),
        )),
      ) as _i11.Future<_i3.SubtaskModel>);

  @override
  _i11.Future<void> deleteSubtaskAndUpdateParent(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSubtaskAndUpdateParent,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
}

/// A class which mocks [MoodService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoodService extends _i1.Mock implements _i14.MoodService {
  MockMoodService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<List<_i4.MoodModel>> getAllMoods() => (super.noSuchMethod(
        Invocation.method(
          #getAllMoods,
          [],
        ),
        returnValue: _i11.Future<List<_i4.MoodModel>>.value(<_i4.MoodModel>[]),
      ) as _i11.Future<List<_i4.MoodModel>>);

  @override
  _i11.Future<_i4.MoodModel?> getMoodById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getMoodById,
          [id],
        ),
        returnValue: _i11.Future<_i4.MoodModel?>.value(),
      ) as _i11.Future<_i4.MoodModel?>);

  @override
  _i11.Future<_i4.MoodModel> createMood(_i4.MoodModel? mood) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMood,
          [mood],
        ),
        returnValue: _i11.Future<_i4.MoodModel>.value(_FakeMoodModel_2(
          this,
          Invocation.method(
            #createMood,
            [mood],
          ),
        )),
      ) as _i11.Future<_i4.MoodModel>);

  @override
  _i11.Future<_i4.MoodModel> updateMood(
    String? id,
    _i4.MoodModel? mood,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMood,
          [
            id,
            mood,
          ],
        ),
        returnValue: _i11.Future<_i4.MoodModel>.value(_FakeMoodModel_2(
          this,
          Invocation.method(
            #updateMood,
            [
              id,
              mood,
            ],
          ),
        )),
      ) as _i11.Future<_i4.MoodModel>);

  @override
  _i11.Future<void> deleteMood(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteMood,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  String generateId() => (super.noSuchMethod(
        Invocation.method(
          #generateId,
          [],
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #generateId,
            [],
          ),
        ),
      ) as String);

  @override
  _i11.Future<String> getCurrentUserId() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserId,
          [],
        ),
        returnValue: _i11.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #getCurrentUserId,
            [],
          ),
        )),
      ) as _i11.Future<String>);

  @override
  _i11.Future<List<_i4.MoodModel>> getMoodsForDate(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMoodsForDate,
          [date],
        ),
        returnValue: _i11.Future<List<_i4.MoodModel>>.value(<_i4.MoodModel>[]),
      ) as _i11.Future<List<_i4.MoodModel>>);
}

/// A class which mocks [HabitService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHabitService extends _i1.Mock implements _i15.HabitService {
  MockHabitService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<List<_i5.HabitModel>> getAllHabits() => (super.noSuchMethod(
        Invocation.method(
          #getAllHabits,
          [],
        ),
        returnValue:
            _i11.Future<List<_i5.HabitModel>>.value(<_i5.HabitModel>[]),
      ) as _i11.Future<List<_i5.HabitModel>>);

  @override
  _i11.Future<_i5.HabitModel?> getHabitById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getHabitById,
          [id],
        ),
        returnValue: _i11.Future<_i5.HabitModel?>.value(),
      ) as _i11.Future<_i5.HabitModel?>);

  @override
  _i11.Future<_i5.HabitModel> createHabit(_i5.HabitModel? habit) =>
      (super.noSuchMethod(
        Invocation.method(
          #createHabit,
          [habit],
        ),
        returnValue: _i11.Future<_i5.HabitModel>.value(_FakeHabitModel_3(
          this,
          Invocation.method(
            #createHabit,
            [habit],
          ),
        )),
      ) as _i11.Future<_i5.HabitModel>);

  @override
  _i11.Future<_i5.HabitModel> updateHabit(
    String? id,
    _i5.HabitModel? habit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateHabit,
          [
            id,
            habit,
          ],
        ),
        returnValue: _i11.Future<_i5.HabitModel>.value(_FakeHabitModel_3(
          this,
          Invocation.method(
            #updateHabit,
            [
              id,
              habit,
            ],
          ),
        )),
      ) as _i11.Future<_i5.HabitModel>);

  @override
  _i11.Future<void> deleteHabit(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteHabit,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<List<_i5.HabitModel>> getHabitsForDate(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHabitsForDate,
          [date],
        ),
        returnValue:
            _i11.Future<List<_i5.HabitModel>>.value(<_i5.HabitModel>[]),
      ) as _i11.Future<List<_i5.HabitModel>>);

  @override
  String generateId() => (super.noSuchMethod(
        Invocation.method(
          #generateId,
          [],
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #generateId,
            [],
          ),
        ),
      ) as String);

  @override
  _i11.Future<String> getCurrentUserId() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserId,
          [],
        ),
        returnValue: _i11.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #getCurrentUserId,
            [],
          ),
        )),
      ) as _i11.Future<String>);
}

/// A class which mocks [SymptomService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSymptomService extends _i1.Mock implements _i16.SymptomService {
  MockSymptomService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<List<_i6.SymptomModel>> getAllSymptoms() => (super.noSuchMethod(
        Invocation.method(
          #getAllSymptoms,
          [],
        ),
        returnValue:
            _i11.Future<List<_i6.SymptomModel>>.value(<_i6.SymptomModel>[]),
      ) as _i11.Future<List<_i6.SymptomModel>>);

  @override
  _i11.Future<_i6.SymptomModel?> getSymptomById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSymptomById,
          [id],
        ),
        returnValue: _i11.Future<_i6.SymptomModel?>.value(),
      ) as _i11.Future<_i6.SymptomModel?>);

  @override
  _i11.Future<_i6.SymptomModel> createSymptom(_i6.SymptomModel? symptom) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSymptom,
          [symptom],
        ),
        returnValue: _i11.Future<_i6.SymptomModel>.value(_FakeSymptomModel_4(
          this,
          Invocation.method(
            #createSymptom,
            [symptom],
          ),
        )),
      ) as _i11.Future<_i6.SymptomModel>);

  @override
  _i11.Future<_i6.SymptomModel> updateSymptom(
    String? id,
    _i6.SymptomModel? symptom,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSymptom,
          [
            id,
            symptom,
          ],
        ),
        returnValue: _i11.Future<_i6.SymptomModel>.value(_FakeSymptomModel_4(
          this,
          Invocation.method(
            #updateSymptom,
            [
              id,
              symptom,
            ],
          ),
        )),
      ) as _i11.Future<_i6.SymptomModel>);

  @override
  _i11.Future<void> deleteSymptom(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteSymptom,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<List<_i6.SymptomModel>> getSymptomsForDate(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSymptomsForDate,
          [date],
        ),
        returnValue:
            _i11.Future<List<_i6.SymptomModel>>.value(<_i6.SymptomModel>[]),
      ) as _i11.Future<List<_i6.SymptomModel>>);

  @override
  String generateId() => (super.noSuchMethod(
        Invocation.method(
          #generateId,
          [],
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #generateId,
            [],
          ),
        ),
      ) as String);

  @override
  _i11.Future<String> getCurrentUserId() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserId,
          [],
        ),
        returnValue: _i11.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #getCurrentUserId,
            [],
          ),
        )),
      ) as _i11.Future<String>);
}

/// A class which mocks [EnergyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEnergyService extends _i1.Mock implements _i17.EnergyService {
  MockEnergyService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<List<_i7.EnergyModel>> getAllEnergyEntries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllEnergyEntries,
          [],
        ),
        returnValue:
            _i11.Future<List<_i7.EnergyModel>>.value(<_i7.EnergyModel>[]),
      ) as _i11.Future<List<_i7.EnergyModel>>);

  @override
  _i11.Future<_i7.EnergyModel?> getEnergyById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEnergyById,
          [id],
        ),
        returnValue: _i11.Future<_i7.EnergyModel?>.value(),
      ) as _i11.Future<_i7.EnergyModel?>);

  @override
  _i11.Future<_i7.EnergyModel> createEnergy(_i7.EnergyModel? energy) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEnergy,
          [energy],
        ),
        returnValue: _i11.Future<_i7.EnergyModel>.value(_FakeEnergyModel_5(
          this,
          Invocation.method(
            #createEnergy,
            [energy],
          ),
        )),
      ) as _i11.Future<_i7.EnergyModel>);

  @override
  _i11.Future<_i7.EnergyModel> updateEnergy(
    String? id,
    _i7.EnergyModel? energy,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEnergy,
          [
            id,
            energy,
          ],
        ),
        returnValue: _i11.Future<_i7.EnergyModel>.value(_FakeEnergyModel_5(
          this,
          Invocation.method(
            #updateEnergy,
            [
              id,
              energy,
            ],
          ),
        )),
      ) as _i11.Future<_i7.EnergyModel>);

  @override
  _i11.Future<void> deleteEnergy(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteEnergy,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  String generateId() => (super.noSuchMethod(
        Invocation.method(
          #generateId,
          [],
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #generateId,
            [],
          ),
        ),
      ) as String);

  @override
  _i11.Future<String> getCurrentUserId() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserId,
          [],
        ),
        returnValue: _i11.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #getCurrentUserId,
            [],
          ),
        )),
      ) as _i11.Future<String>);

  @override
  _i11.Future<_i7.EnergyModel?> getLastEnergyEntry() => (super.noSuchMethod(
        Invocation.method(
          #getLastEnergyEntry,
          [],
        ),
        returnValue: _i11.Future<_i7.EnergyModel?>.value(),
      ) as _i11.Future<_i7.EnergyModel?>);

  @override
  _i11.Future<List<_i7.EnergyModel>> getEnergyEntriesForDate(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEnergyEntriesForDate,
          [date],
        ),
        returnValue:
            _i11.Future<List<_i7.EnergyModel>>.value(<_i7.EnergyModel>[]),
      ) as _i11.Future<List<_i7.EnergyModel>>);
}

/// A class which mocks [FlowmodoroService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlowmodoroService extends _i1.Mock implements _i18.FlowmodoroService {
  MockFlowmodoroService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<List<_i8.FlowmodoroModel>> getAllFlowmodoro() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllFlowmodoro,
          [],
        ),
        returnValue: _i11.Future<List<_i8.FlowmodoroModel>>.value(
            <_i8.FlowmodoroModel>[]),
      ) as _i11.Future<List<_i8.FlowmodoroModel>>);

  @override
  _i11.Future<_i8.FlowmodoroModel?> getFlowmodoroById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFlowmodoroById,
          [id],
        ),
        returnValue: _i11.Future<_i8.FlowmodoroModel?>.value(),
      ) as _i11.Future<_i8.FlowmodoroModel?>);

  @override
  _i11.Future<_i8.FlowmodoroModel> createFlowmodoro(
          _i8.FlowmodoroModel? flowmodoro) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFlowmodoro,
          [flowmodoro],
        ),
        returnValue:
            _i11.Future<_i8.FlowmodoroModel>.value(_FakeFlowmodoroModel_6(
          this,
          Invocation.method(
            #createFlowmodoro,
            [flowmodoro],
          ),
        )),
      ) as _i11.Future<_i8.FlowmodoroModel>);

  @override
  _i11.Future<_i8.FlowmodoroModel> updateFlowmodoro(
    String? id,
    _i8.FlowmodoroModel? flowmodoro,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFlowmodoro,
          [
            id,
            flowmodoro,
          ],
        ),
        returnValue:
            _i11.Future<_i8.FlowmodoroModel>.value(_FakeFlowmodoroModel_6(
          this,
          Invocation.method(
            #updateFlowmodoro,
            [
              id,
              flowmodoro,
            ],
          ),
        )),
      ) as _i11.Future<_i8.FlowmodoroModel>);

  @override
  _i11.Future<void> deleteFlowmodoro(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteFlowmodoro,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<List<_i8.FlowmodoroModel>> getFlowmodorosForDate(
          DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFlowmodorosForDate,
          [date],
        ),
        returnValue: _i11.Future<List<_i8.FlowmodoroModel>>.value(
            <_i8.FlowmodoroModel>[]),
      ) as _i11.Future<List<_i8.FlowmodoroModel>>);
}

/// A class which mocks [MedicationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedicationService extends _i1.Mock implements _i19.MedicationService {
  MockMedicationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<List<_i9.MedicationModel>> getAllMedications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllMedications,
          [],
        ),
        returnValue: _i11.Future<List<_i9.MedicationModel>>.value(
            <_i9.MedicationModel>[]),
      ) as _i11.Future<List<_i9.MedicationModel>>);

  @override
  _i11.Future<_i9.MedicationModel?> getMedicationById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMedicationById,
          [id],
        ),
        returnValue: _i11.Future<_i9.MedicationModel?>.value(),
      ) as _i11.Future<_i9.MedicationModel?>);

  @override
  _i11.Future<_i9.MedicationModel> createMedication(
          _i9.MedicationModel? medication) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMedication,
          [medication],
        ),
        returnValue:
            _i11.Future<_i9.MedicationModel>.value(_FakeMedicationModel_7(
          this,
          Invocation.method(
            #createMedication,
            [medication],
          ),
        )),
      ) as _i11.Future<_i9.MedicationModel>);

  @override
  _i11.Future<_i9.MedicationModel> updateMedication(
    String? id,
    _i9.MedicationModel? medication,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMedication,
          [
            id,
            medication,
          ],
        ),
        returnValue:
            _i11.Future<_i9.MedicationModel>.value(_FakeMedicationModel_7(
          this,
          Invocation.method(
            #updateMedication,
            [
              id,
              medication,
            ],
          ),
        )),
      ) as _i11.Future<_i9.MedicationModel>);

  @override
  _i11.Future<void> deleteMedication(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteMedication,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<List<_i9.MedicationModel>> getMedicationsForDate(
          DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMedicationsForDate,
          [date],
        ),
        returnValue: _i11.Future<List<_i9.MedicationModel>>.value(
            <_i9.MedicationModel>[]),
      ) as _i11.Future<List<_i9.MedicationModel>>);

  @override
  String generateId() => (super.noSuchMethod(
        Invocation.method(
          #generateId,
          [],
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #generateId,
            [],
          ),
        ),
      ) as String);

  @override
  _i11.Future<String> getCurrentUserId() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserId,
          [],
        ),
        returnValue: _i11.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #getCurrentUserId,
            [],
          ),
        )),
      ) as _i11.Future<String>);
}
