// Mocks generated by Mockito 5.4.6 from annotations
// in spiceease/test/features/time_management/flowmodoro/flowmodoro_functionality_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:spiceease/data/models/flowmodoro_model.dart' as _i4;
import 'package:spiceease/data/models/subtask_model.dart' as _i3;
import 'package:spiceease/data/models/task_model.dart' as _i2;
import 'package:spiceease/data/services/flowmodoro_service.dart' as _i9;
import 'package:spiceease/data/services/subtask_service.dart' as _i8;
import 'package:spiceease/data/services/task_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTaskModel_0 extends _i1.SmartFake implements _i2.TaskModel {
  _FakeTaskModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSubtaskModel_1 extends _i1.SmartFake implements _i3.SubtaskModel {
  _FakeSubtaskModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlowmodoroModel_2 extends _i1.SmartFake
    implements _i4.FlowmodoroModel {
  _FakeFlowmodoroModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TaskService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskService extends _i1.Mock implements _i5.TaskService {
  MockTaskService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i2.TaskModel>> getAllTasks() => (super.noSuchMethod(
        Invocation.method(
          #getAllTasks,
          [],
        ),
        returnValue: _i6.Future<List<_i2.TaskModel>>.value(<_i2.TaskModel>[]),
      ) as _i6.Future<List<_i2.TaskModel>>);

  @override
  _i6.Future<_i2.TaskModel?> getTaskById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getTaskById,
          [id],
        ),
        returnValue: _i6.Future<_i2.TaskModel?>.value(),
      ) as _i6.Future<_i2.TaskModel?>);

  @override
  _i6.Future<_i2.TaskModel> createTask(_i2.TaskModel? task) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTask,
          [task],
        ),
        returnValue: _i6.Future<_i2.TaskModel>.value(_FakeTaskModel_0(
          this,
          Invocation.method(
            #createTask,
            [task],
          ),
        )),
      ) as _i6.Future<_i2.TaskModel>);

  @override
  _i6.Future<_i2.TaskModel> updateTask(
    String? id,
    _i2.TaskModel? task,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [
            id,
            task,
          ],
        ),
        returnValue: _i6.Future<_i2.TaskModel>.value(_FakeTaskModel_0(
          this,
          Invocation.method(
            #updateTask,
            [
              id,
              task,
            ],
          ),
        )),
      ) as _i6.Future<_i2.TaskModel>);

  @override
  _i6.Future<void> deleteTask(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i2.TaskModel>> getTasksForDate(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksForDate,
          [date],
        ),
        returnValue: _i6.Future<List<_i2.TaskModel>>.value(<_i2.TaskModel>[]),
      ) as _i6.Future<List<_i2.TaskModel>>);

  @override
  String generateId() => (super.noSuchMethod(
        Invocation.method(
          #generateId,
          [],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #generateId,
            [],
          ),
        ),
      ) as String);

  @override
  _i6.Future<String> getCurrentUserId() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserId,
          [],
        ),
        returnValue: _i6.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #getCurrentUserId,
            [],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<List<_i2.TaskModel>> getTasksByStatus(
    String? status, {
    bool? sortByPriority = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksByStatus,
          [status],
          {#sortByPriority: sortByPriority},
        ),
        returnValue: _i6.Future<List<_i2.TaskModel>>.value(<_i2.TaskModel>[]),
      ) as _i6.Future<List<_i2.TaskModel>>);

  @override
  _i6.Future<void> toggleTaskCompletion(
    String? taskId,
    DateTime? selectedDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleTaskCompletion,
          [
            taskId,
            selectedDate,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [SubtaskService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubtaskService extends _i1.Mock implements _i8.SubtaskService {
  MockSubtaskService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i3.SubtaskModel>> getAllSubtasks() => (super.noSuchMethod(
        Invocation.method(
          #getAllSubtasks,
          [],
        ),
        returnValue:
            _i6.Future<List<_i3.SubtaskModel>>.value(<_i3.SubtaskModel>[]),
      ) as _i6.Future<List<_i3.SubtaskModel>>);

  @override
  _i6.Future<_i3.SubtaskModel?> getSubtaskById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubtaskById,
          [id],
        ),
        returnValue: _i6.Future<_i3.SubtaskModel?>.value(),
      ) as _i6.Future<_i3.SubtaskModel?>);

  @override
  _i6.Future<_i3.SubtaskModel> createSubtask(_i3.SubtaskModel? subtask) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSubtask,
          [subtask],
        ),
        returnValue: _i6.Future<_i3.SubtaskModel>.value(_FakeSubtaskModel_1(
          this,
          Invocation.method(
            #createSubtask,
            [subtask],
          ),
        )),
      ) as _i6.Future<_i3.SubtaskModel>);

  @override
  _i6.Future<_i3.SubtaskModel> updateSubtask(
    String? id,
    _i3.SubtaskModel? subtask,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSubtask,
          [
            id,
            subtask,
          ],
        ),
        returnValue: _i6.Future<_i3.SubtaskModel>.value(_FakeSubtaskModel_1(
          this,
          Invocation.method(
            #updateSubtask,
            [
              id,
              subtask,
            ],
          ),
        )),
      ) as _i6.Future<_i3.SubtaskModel>);

  @override
  _i6.Future<void> deleteSubtask(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteSubtask,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i3.SubtaskModel>> getSubtasksForTask(String? taskId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubtasksForTask,
          [taskId],
        ),
        returnValue:
            _i6.Future<List<_i3.SubtaskModel>>.value(<_i3.SubtaskModel>[]),
      ) as _i6.Future<List<_i3.SubtaskModel>>);

  @override
  _i6.Future<_i3.SubtaskModel> createSubtaskAndUpdateParent(
          _i3.SubtaskModel? subtask) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSubtaskAndUpdateParent,
          [subtask],
        ),
        returnValue: _i6.Future<_i3.SubtaskModel>.value(_FakeSubtaskModel_1(
          this,
          Invocation.method(
            #createSubtaskAndUpdateParent,
            [subtask],
          ),
        )),
      ) as _i6.Future<_i3.SubtaskModel>);

  @override
  _i6.Future<void> deleteSubtaskAndUpdateParent(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSubtaskAndUpdateParent,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [FlowmodoroService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlowmodoroService extends _i1.Mock implements _i9.FlowmodoroService {
  MockFlowmodoroService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i4.FlowmodoroModel>> getAllFlowmodoro() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllFlowmodoro,
          [],
        ),
        returnValue: _i6.Future<List<_i4.FlowmodoroModel>>.value(
            <_i4.FlowmodoroModel>[]),
      ) as _i6.Future<List<_i4.FlowmodoroModel>>);

  @override
  _i6.Future<_i4.FlowmodoroModel?> getFlowmodoroById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFlowmodoroById,
          [id],
        ),
        returnValue: _i6.Future<_i4.FlowmodoroModel?>.value(),
      ) as _i6.Future<_i4.FlowmodoroModel?>);

  @override
  _i6.Future<_i4.FlowmodoroModel> createFlowmodoro(
          _i4.FlowmodoroModel? flowmodoro) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFlowmodoro,
          [flowmodoro],
        ),
        returnValue:
            _i6.Future<_i4.FlowmodoroModel>.value(_FakeFlowmodoroModel_2(
          this,
          Invocation.method(
            #createFlowmodoro,
            [flowmodoro],
          ),
        )),
      ) as _i6.Future<_i4.FlowmodoroModel>);

  @override
  _i6.Future<_i4.FlowmodoroModel> updateFlowmodoro(
    String? id,
    _i4.FlowmodoroModel? flowmodoro,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFlowmodoro,
          [
            id,
            flowmodoro,
          ],
        ),
        returnValue:
            _i6.Future<_i4.FlowmodoroModel>.value(_FakeFlowmodoroModel_2(
          this,
          Invocation.method(
            #updateFlowmodoro,
            [
              id,
              flowmodoro,
            ],
          ),
        )),
      ) as _i6.Future<_i4.FlowmodoroModel>);

  @override
  _i6.Future<void> deleteFlowmodoro(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteFlowmodoro,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i4.FlowmodoroModel>> getFlowmodorosForDate(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFlowmodorosForDate,
          [date],
        ),
        returnValue: _i6.Future<List<_i4.FlowmodoroModel>>.value(
            <_i4.FlowmodoroModel>[]),
      ) as _i6.Future<List<_i4.FlowmodoroModel>>);
}
